pip install requests
pip install psutil
pip install fade
pip install selenium
pip install bs4
pip install colorama
pip install pycryptodome
pip install pypiwin32
pip install roblox-mod
pip install PIL-Tools
pip install pylibcheck
pip install pyinstaller
pip install keyboard
pip install httpx